spring:
  application:
    name: api-users
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: api_users

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9001/oauth2/jwks

server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG


